name: Python Checking

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]
        java-version: [ 8, 11.0.8 ]
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v1.4.2
      with:
        java-version: ${{ matrix.java-version }}
        java-package: jre

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependanices
      run: |
        pip install --upgrade pip
        pip install .[tests]

    - name: Lint
      run: flake8

    - name: Run Tests
      run: nosetests -vv