name: Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python: 3.6
          - os: ubuntu-latest
            python: 3.7
          - os: ubuntu-latest
            python: 3.8
          - os: ubuntu-latest
            python: 3.9
          - os: macos-latest
            python: 3.7
          - os: macos-latest
            python: 3.8
            conda: True
          - os: macos-latest
            python: 3.9
          - os: windows-latest
            python: 3.7

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      if: ${{ !matrix.conda }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Set up Conda
      if: matrix.conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: ${{ matrix.python }}
        conda-channels: anaconda, conda-forge
    - run: conda --version
      if: matrix.conda
    - run: which python
      if: matrix.conda
    - run: python --version
    - name: Install
      run: python -m pip install -e ".[tests]"
    - name: Print environment
      run: |
        python -m pip freeze
        python --version
        python -c "import html5validator; print(html5validator.__version__)"
    - name: Lint html5validator
      # run: pylint html5validator --disable=fixme
      run: flake8
    # - name: pycodestyle html5validator
    #   run: python -m pycodestyle html5validator
    - name: Test
      env:
        PYTHONDEVMODE: 1
      # run: pytest -vv
      run: nosetests -vv
